### ISSUE TITLE
Need to refine the format to be kind of compatible with ASCII ESRI/GeoJson/TopoJSON etc 

### ISSUE THREAD

**Issue by agrignard** [ChangingPlaces/DataTemplates#2]
We can start here to discuss about what we want in the our MDJson.
 I think this repository needs some intention or might be integrated some how in CityIOServer as a kind of test/documentation
    NCOLS xxx
    NROWS xxx
    XLLCENTER xxx | XLLCORNER xxx
    YLLCENTER xxx | YLLCORNER xxx
    CELLSIZE xxx
    NODATA_VALUE xxx
    row 1
    row 2
    ...
    row n

**Comment by yasushisakai** [comment]
although the server is agnostic to the actual data, if were to start on validation and taking deltas,
I think the server script will need to know the data structure to some degree.

(It is already comparing data for ```objects``` and ```grid``` for ditch duplicates)

so, +1 on migrating this to [cityioserver](https://github.com/mitmedialab/cityioserver)

**Comment by RELNO** [comment]
Given recent cityio dev, can we maybe close this?
